version: "3.8"

services:
  back:
    image: phapp_back:0.1
    container_name: back
    build:
      context: ./back
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
      - PRODUCT_HUNT_URL=${PRODUCT_HUNT_URL}
      - PRODUCT_HUNT_TOKEN=${PRODUCT_HUNT_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://back:${PORT}/api"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - 5000:5000
    restart: on-failure
    networks:
      - phapp
  front:
    image: phapp_front:0.1
    container_name: front
    build:
      context: ./front
    restart: on-failure
    ports:
      - 80:80
    networks:
      - phapp

networks:
  phapp:
    driver: bridge
